
name: Build Mark-XLVI EXE

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List all files in repo
        run: Get-ChildItem -Recurse | Select-Object FullName
